GET http://localhost:3000/votes
Content-Type: application/json

###

POST http://localhost:3000/votes
Content-Type: application/json

{ "animal": "Cat" }

###

POST http://localhost:3000/votes
Content-Type: application/json

{ "animal": "Dog" }

###

POST http://localhost:3000/votes
Content-Type: application/json

{ "animal": "Cat", "subscription": { "name":  "Jon Doe", "email":  "jon@doe.com" } }
